### ISSUE TITLE
can't build new contents

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant#120] opened 2016-07-22 11:33 UTC
```bash
$ preupg-xccdf-compose RHEL6_7

********** ERROR **********
The file RHEL6_7-results/services/backup_tomcat/check.sh is not executable 
Traceback (most recent call last):
  File "../preupgrade-assistant/preupg-xccdf-compose", line 42, in <module>
    main()
  File "../preupgrade-assistant/preupg-xccdf-compose", line 32, in main
    xccdf_compose.generate_xml(generate_from_ini=True)
  File "/home/pstodulk/special/preupgrade-assistant/preuputils/compose.py", line 63, in generate_xml
    target_tree = ComposeXML.run_compose(target_tree, self.dir_name, generate_from_ini=generate_from_ini)
  File "/home/pstodulk/special/preupgrade-assistant/preuputils/compose.py", line 319, in run_compose
    group_xmls = cls.collect_group_xmls(dir_name, content=content, level=0, generate_from_ini=generate_from_ini)
  File "/home/pstodulk/special/preupgrade-assistant/preuputils/compose.py", line 113, in collect_group_xmls
    cls.collect_group_xmls(new_dir, level=level + 1, generate_from_ini=generate_from_ini))
  File "/home/pstodulk/special/preupgrade-assistant/preuputils/compose.py", line 103, in collect_group_xmls
    oscap_group.write_xml()
  File "/home/pstodulk/special/preupgrade-assistant/preuputils/oscap_group_xml.py", line 99, in write_xml
    self.rule = xml_utils.prepare_sections()
  File "/home/pstodulk/special/preupgrade-assistant/preuputils/xml_utils.py", line 214, in prepare_sections
    self.create_xml_from_ini(main)
  File "/home/pstodulk/special/preupgrade-assistant/preuputils/xml_utils.py", line 337, in create_xml_from_ini
    function(key, k)
  File "/home/pstodulk/special/preupgrade-assistant/preuputils/xml_utils.py", line 237, in fnc_check_script
    self.check_script_modification(key, name)
  File "/home/pstodulk/special/preupgrade-assistant/preuputils/xml_utils.py", line 201, in check_script_modification
    self.mh.update_check_script(updates, author=author)
  File "/home/pstodulk/special/preupgrade-assistant/preuputils/script_utils.py", line 123, in update_check_script
    generated_section, functions = ModuleHelper.generate_common_stuff(settings.license % author,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 9: ordinal not in range(128)
```

**Comment by phracek** [comment] 2016-07-27 09:01
Did you build them from the latest GitHub repo?
I am not able to reproduce it.

**Comment by phracek** [comment] 2016-07-27 11:06
You are right, I don't know what is happend on my RHEL-6 machine, but I have a reproducer. Fixing it soon.

**Comment by phracek** [comment] 2016-07-28 09:49
Fixed by this commit https://github.com/upgrades-migrations/preupgrade-assistant/commit/cd4db13df945b212fc7ceb6333137526e724f782

**Closed by phracek** 2016-07-28 09:49 UTC
Labels: bug
